services:
  db:
    image: postgres:14-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080

  server:
    image: test-rust-api
    build:
      context: .
    ports:
      - 3000:3000
    environment:
      - LOG_LEVEL=debug
      - DATABASE_HOST=db
    links:
      - db

volumes:
  database:
