[package]
name = "api"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
tokio = { workspace = true }
logger = { path = "../../libs/logger" }
database = { path = "../../libs/database" }
anyhow = { workspace = true }
dotenv = { workspace = true }
